/* Generated By:JavaCC: Do not edit this line. parseConstants.java */
package drz.oddb.parse;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface parseConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int SEMICOLON = 5;
  /** RegularExpression Id. */
  int CREATE = 6;
  /** RegularExpression Id. */
  int DROP = 7;
  /** RegularExpression Id. */
  int CLASS = 8;
  /** RegularExpression Id. */
  int INSERT = 9;
  /** RegularExpression Id. */
  int UNION = 10;
  /** RegularExpression Id. */
  int INTO = 11;
  /** RegularExpression Id. */
  int VALUES = 12;
  /** RegularExpression Id. */
  int LEFT_BRACKET = 13;
  /** RegularExpression Id. */
  int COMMA = 14;
  /** RegularExpression Id. */
  int RIGHT_BRACKET = 15;
  /** RegularExpression Id. */
  int DELETE = 16;
  /** RegularExpression Id. */
  int FROM = 17;
  /** RegularExpression Id. */
  int WHERE = 18;
  /** RegularExpression Id. */
  int SELECT = 19;
  /** RegularExpression Id. */
  int SELECTDEPUTY = 20;
  /** RegularExpression Id. */
  int UNIONDEPUTYCLASS = 21;
  /** RegularExpression Id. */
  int ID = 22;
  /** RegularExpression Id. */
  int EQUAL = 23;
  /** RegularExpression Id. */
  int INT = 24;
  /** RegularExpression Id. */
  int STRING = 25;
  /** RegularExpression Id. */
  int CROSS = 26;
  /** RegularExpression Id. */
  int DOT = 27;
  /** RegularExpression Id. */
  int AS = 28;
  /** RegularExpression Id. */
  int PLUS = 29;
  /** RegularExpression Id. */
  int UPDATE = 30;
  /** RegularExpression Id. */
  int SET = 31;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\";\"",
    "\"CREATE\"",
    "\"DROP\"",
    "\"CLASS\"",
    "\"INSERT\"",
    "\"UNION\"",
    "\"INTO\"",
    "\"VALUES\"",
    "\"(\"",
    "\",\"",
    "\")\"",
    "\"DELETE\"",
    "\"FROM\"",
    "\"WHERE\"",
    "\"SELECT\"",
    "\"SELECTDEPUTY\"",
    "\"UNIONDEPUTYCLASS\"",
    "<ID>",
    "\"=\"",
    "<INT>",
    "<STRING>",
    "\"->\"",
    "\".\"",
    "\"AS\"",
    "\"+\"",
    "\"UPDATE\"",
    "\"SET\"",
  };

}
